# Generated by Django 2.2.7 on 2019-12-10 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingrediente', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=16)),
                ('cantidad', models.IntegerField(default=1)),
                ('imagen', models.ImageField(max_length=255, null=True, upload_to='pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roles', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Rol',
                'ordering': ['roles'],
            },
        ),
        migrations.CreateModel(
            name='TipoIngrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('ingrediente', models.ManyToManyField(to='pedidos.Ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_pedido', models.DateTimeField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('atendidopor', models.CharField(blank=True, max_length=255, null=True)),
                ('detallepedido', models.ManyToManyField(to='pedidos.DetallePedido')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.EstadoPedido')),
            ],
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Ingrediente'),
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Localidad', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Rol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaborador',
                'ordering': ['edad'],
            },
        ),
    ]
