# Generated by Django 2.2.7 on 2019-12-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20191208_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='detallepedido',
            field=models.ManyToManyField(related_name='detallepedido', to='pedidos.DetallePedido'),
        ),
    ]
